name: CI / CD for Zilean

on:
  push:
    tag:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  IMAGE_NAME: ipromknight/zilean

jobs:
  execution:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Build Zilean Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
        id: qemu
        with:
          platforms: amd64,arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Build Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            type=ref,event=tag
            type=sha,commit=${{ github.sha }}
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Push Service Image to repo
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: mode=max
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}